package com.dyrosoft.kvbparser;


public class TestPages {

    public static final String DEPARTURES = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"de\" lang=\"de\">\n"
            + "<head>\n"
            + "<title>K&ouml;lner Verkehrs-Betriebe AG</title>\n"
            + "<meta name=\"author\" content=\"Vipex Media Services GmbH | www.vipex.de | CMS: AdOvo www.adovo.de\" />\n"
            + "<meta name=\"copyright\" content=\"Kölner Verkehrs-Betriebe AG Unternehmenskommunikation\" />\n"
            + "<meta name=\"language\" content=\"de\" />\n"
            + "<meta name=\"robots\" content=\"INDEX,FOLLOW\" />\n"
            + "<meta name=\"page-topic\" content=\"Kölner Verkehrs-Betriebe AG\" />\n"
            + "<meta name=\"audience\" content=\"Alle\" />\n"
            + "<meta name=\"content-language\" content=\"DE, deutsch\" />\n"
            + "<meta name=\"revisit-after\" content=\"2 days\" />\n"
            + "<meta name=\"description\" content=\"\" />\n"
            + "<meta name=\"keywords\" content=\"\" />\n"
            + "<meta content=\"text/html; charset=ISO-8859-1\" http-equiv=\"Content-Type\" />\n"
            + "<meta name=\"robots\" content=\"index, follow\" />\n"
            + "<!--<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />-->\n"
            + "<!--<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />-->\n"
            + "<link rel=\"stylesheet\" href=\"/css/kvb.v2.css?20130319\" type=\"text/css\" media=\"Screen\" />\n"
            + "\n"
            + "<style type=\"text/css\">\n"
            + "#wrapper {\n"
            + "    background-image: url(/images/tpl/bg_menue_content_sidebar2.jpg);\n"
            + "\tbackground-repeat: repeat-y;\n"
            + "\n"
            + "}\n"
            + "</style>\n"
            + "<meta http-equiv=\"refresh\" content=\"60\" />\n"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1\" />\n"
            + "<link href=\"/css/kvb.v2.mobil.css\" rel=\"stylesheet\" type=\"text/css\" />\n"
            + "\n"
            + "<style type=\"text/css\">\n"
            + "@media only screen and (max-device-width: 675px), only screen and (max-width: 675px) {\n"
            + ".grau_seiten { padding: 0%!important; }.grau_bg { background-color:#fff; }\n"
            + "}\n"
            + "</style>\n"
            + "<script src=\"/skripte/jquery-1.2.6.min.js\" type=\"text/javascript\"></script>\n"
            + "<script type=\"text/javascript\">\n"
            + "    var _gaq = _gaq || [];\n"
            + "    _gaq.push(['_setAccount', 'UA-32570981-1']);\n"
            + "    _gaq.push(['_gat._anonymizeIp']);\n"
            + "    _gaq.push(['_trackPageview']);\n"
            + "    (function() {\n"
            + "    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n"
            + "    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n"
            + "    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n"
            + "    })();\n"
            + "</script>\n"
            + "<style type=\"text/css\">\n"
            + ".mofisanzeigen\n"
            + "{\n"
            + "\t/*display: none;*/\n"
            + "}\n"
            + "</style>\n"
            + "</head>\n"
            + "<body>\n"
            + "<center>\n"
            + "<div class=\"mobileheader mobileshow\" style=\"display:none;\">\n"
            + "\t<img id=\"menubutton\" src=\"/images/tpl/mobile_menu_icon.png\" style=\"float:right;cursor:pointer;\" alt=\"Men&uuml;\" width=\"36\" />\n"
            + "\t<a href=\"/german/home/\" style=\"color:#000000;text-decoration:none;\">Kölner Verkehrs-Betriebe AG<br />KVB - Menschen bewegen.<br /></a>\n"
            + "\t\t<div id=\"mobilemenuopen\" style=\"display:none;\">\n"
            + "\t<ul class=\"mobile_menu\">\n"
            + "\t<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/german/fahrplan/index.html\">Fahrpläne und mehr</a><ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/fahrplan/app/index.html\">KVB-App</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/fahrplanwechsel15.html\">Fahrplanwechsel 2015</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/fahrplan/fahrplanwechsel15_2.html\">Zusatzinfos zum Fahrplanwechsel</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"http://auskunft.kvb-koeln.de/kvb/cgi/\">Fahrplanauskunft</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/aushangfahrplaene6.html\">Aushangfahrpläne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/minifahrplaene6.html\">Minifahrpläne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/linienplan.html\">Liniennetzpläne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/rufbuslinie187.html\">AST und TaxiBus</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/sprechender_fpl.html\">Sprechender Fahrplan</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/abfahrtsmonitor.html\">AbfahrtsMonitor</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/mofis/mofis.html\">Fahrgastinformationsanzeiger</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/generator/index.html\">Widget Generator</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/hst/index.html\">Haltestellensuche</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/rendezvous.html\">Rendezvousverkehr Nacht-Fahrpläne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/Baustellen.html\">Baustelleninformationen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/fahrrad.html\">KVB & Fahrrad</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/fahrplan/fahrradverleih.html\">KVB-Rad</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/kvb-rad_kontakt.html\">Kontakt KVB-Rad</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/bikesharing.html\">Call a Bike</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/bikeandride.html\">Schließanlagen für private Fahrräder</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/fahrraeder_bedingungen.html\">Regeln für die private Fahrradnutzung</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/stadtauto.html\">KVB & CarSharing</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/fahrplan/carsharing/cambio.html\">cambio</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/carsharing/car2go.html\">car2go</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/carsharing/drivenow.html\">DriveNow</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/carsharing/flinkster.html\">Flinkster</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/parkandride.html\">Park & Ride-Infos</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/hkx.html\">KVB & HKX</a></li>\n"
            + "</ul>\n"
            + "</li>\n"
            + "<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/german/tarif/index.html\">Tarife und Tickets</a><ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/index.html\">Tarifgebiete</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/tarife_koeln.html\">Köln</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/tarifbestimmung.html\">VRS-Netz</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/vrs_erweitert.html\">VRS-Netz erweitert</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/vrr.html\">VRS/VRR</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/ahr.html\">VRS/Ahr</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/avv.html\">VRS/AVV</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/nrw.html\">NRW</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/card.html\">BahnCard</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/tarifgebiete.html\">Preisstufen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/tickets/index.html\">Ticketsortiment</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/einzel.html\">EinzelTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/anschluss.html\">AnschlussTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/mehrfahrten.html\">4erTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/kinder.html\">Kinder</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/tagesticket.html\">TagesTicket</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/24_stunden.html\">TagesTicket 1 Per.</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/minigruppe.html\">TagesTicket 5 Per.</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/wochenticket.html\">WochenTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/monatsticket.html\">MonatsTicket / Abo</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/senioren.html\">Formel 9Ticket / Abo</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/aktiv_60.html\">Aktiv60Ticket / Abo</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/tickets/gruppenticket.html\">GruppenTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/stadt_ticket.html\">MobilPassTickets</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/ausbildungsverkehr.html\">Ausbildungsverkehr</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/starter.html\">StarterTicket / Abo</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/primaticket.html\">PrimaTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/schuelerticket2.html\">SchülerTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/absolventen.html\">AbsolventenTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/tickets/semester_ticket.html\">Semester-/DualTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/handyticket/neu.html\">HandyTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/jobticket.html\">JobTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/tickets_im_abo.html\">Abo</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/neue_tarife/nrw.html\">NRW-Tickets</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/tickets/fahrrad.html\">Fahrradmitnahme</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/koelncard.html\">KölnCard</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/kongressticket.html\">KongressTickets</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/gueltigkeit.html\">Ticketgültigkeiten</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/eng.html\">Tickets and Fares</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/tickets/ihr_weg/ihr_weg.html\">Ihr Weg zum Ticket</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"http://www.kvb-koeln.de/german/tarif/app/index.html\">KVB-App</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/handyticket/neu.html\">HandyTicket</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/tickets_selbst_drucken.html\">Online-TicketShop</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/index.html\">KundenCenter</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/chlodwigplatz.html\">KundenCenter Südstadt</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/neumarkt.html\">KundenCenter Neumarkt</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/muelheim.html\">KundenCenter Mülheim</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/ehrenfeld.html\">KundenCenter Ehrenfeld</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/westforum.html\">KundenCenter Westforum</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/vk_neumarkt.html\">Vertriebsstelle Neumarkt</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/dom.html\">Vertriebsstelle Dom</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/fc/ebertplatz.html\">Vertriebsstelle Ebertplatz</a></li>\n"
            + "</ul>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/index.html\">Beförderungsbedingungen</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/behinderte.html\">Schwerbehinderte</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/erhoeht_2015.html\">Erhöhtes Beförderungsentgelt</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/fahrgastrechte_im_bus.html\">Fahrgastrechte im Bus</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/fahrscheine.html\">Tickets</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/fahrraeder.html\">Fahrräder</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/hunde.html\">Hunde</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/kinder.html\">Kinder</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/polizisten.html\">Polizisten in Uniform</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/aktiv60.html\">Senioren</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/studenten.html\">Studenten</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/tarifkooperation.html\">Tarifkooperationen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/bedingungen/uebergangstarife.html\">Übergangstarife</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/tarif15.html\">Preisanpassung 2016</a></li>\n"
            + "</ul>\n"
            + "</li>\n"
            + "<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/german/news/index.html\">Neues und Service</a><ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/tarif/aktion.html\">Kundenvorteile und aktuelle Aktionen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarif/abo_plus/index.html\">AboPlus-Programm</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/spezial/fahrzeugbegl.html\">Fahrzeugbegleiter</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"http://www.kvb-koeln.de/german/news/barrierefrei.html\">Barrierefrei unterwegs</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"http://www.kvb-koeln.de/german/news/mobitraining.html\">Mobilitätstraining</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/Baustellen.html\">Baustelleninfos</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/news/verfuegbarkeit_aufzuege.html\">Aufzugstörungen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/hw.html\">Projekt: Abstellanlage Weidenpesch</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/kontrolle.html\">Kontrollen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/vorne.html\">Vordereinstieg</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/serviceversprechen.html\">Serviceversprechen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/umfrage_13.html\">Kundenbefragung</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/newsletter/index.html\">Newsletter</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/aktuelles.html\">Aktuelles</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/publikationen.html\">Publikationen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/fundbuero.html\">Fundbüro</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/infomaterial.html\">Infomaterial</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/qr.html\">QR-Code</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/fahrplan/helfen.html\">Hilfe im Notfall</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/tarife/tickets/garantieticket.html\">Mobilitätsgarantie</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/idee.html\">Lob, Kritik und neue Ideen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/news/schaden.html\">Schadensmeldung online</a></li>\n"
            + "</ul>\n"
            + "</li>\n"
            + "<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/german/kampagnen/index.html\">Kampagnen</a><ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/kampagnen/ihr_abo_laeuft.html\">Ihr Abo läuft</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/koeln_steht_bei_rot.html\">Köln steht bei Rot</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/klimaschutz.html\">Klimakampagne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/kurzstrecke.html\">Kurzstrecken-Kampagne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/dialog.html\">Dialogkampagne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/neu_buerger.html\">Neubürgerkampagne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/sauberkeit.html\">Sauberkeitsoffensive</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/pendler_und_helden.html\">Pendler & andere Helden</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/kampagnen/pendler_und_helden_videos.html\">Pendler & andere Helden Folgen 1 bis 5</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/pendler_und_helden_videos_6_10.html\">Pendler & andere Helden Folgen 6 bis 10</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/pendler_und_helden_videos_11_15.html\">Pendler & andere Helden Folgen 11 bis 15</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/pendler_und_helden_videos_16_18.html\">Pendler & andere Helden Folgen 16 bis 18</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/koeln_spart_co2.html\">Köln spart C02</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/themennetzplaene.html\">Themen-Netzpläne</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/kampagnen/nrw_aktionen.html\">NRW-Kampagnen</a></li>\n"
            + "</ul>\n"
            + "</li>\n"
            + "<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/german/cityservice/index.html\">Veranstaltungsinfos</a><ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/cityservice/eroeffnung_17.html\">Eröffnung der Linie 17</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/cityservice/karneval16.html\">Karneval 2015/16</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/cityservice/touren/coloniaexpress.html\">Colonia-Express</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/spezial/colonia_express/index.html\">ColoniaTours</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/spezial/colonia_express/bahn.html\">Bahn</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/spezial/bus/bus.html\">Bus</a></li>\n"
            + "</ul>\n"
            + "</ul>\n"
            + "</ul>\n"
            + "</li>\n"
            + "<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/german/unternehmen/index.html\">Das Unternehmen</a><ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/geschaeftsleitung.html\">Vorstand</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/Aufsichtsrat.html\">Aufsichtsrat</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/kvb/index.html\">Eckdaten</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/unternehmen/kvb/bahn.html\">Bahn</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/kvb/bus.html\">Bus</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/kvb/leitstelle.html\">Leitstelle</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/struktur/hauptwerkstatt.html\">Werkstätten</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/index.html\">Mitarbeiter</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/struktur.html\">Struktur</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/leitbild.html\">Leitbild</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/personal.html\">Personal</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/Betriebsrat.html\">Betriebsrat</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/korruption.html\">Korruptionsrichtlinie</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/mitarbeiter/ombud.html\">Compliance-Management</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/themen/index.html\">Themen</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/unternehmen/themen/flexibilisierung.html\">Arbeitszeitflexibilisierung</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/themen/instrumente.html\">Personalmanagementsysteme</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/themen/vorschlagswesen.html\">Ideenmanagement</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/leistungsdaten/index.html\">Leistungsdaten</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/unternehmen/leistungsdaten/bahn.html\">Bahn</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/leistungsdaten/bus.html\">Bus</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/leistungsdaten/jahre.html\">Bilanz</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/leistungsdaten/geschaeftsbericht.html\">Geschäftsbericht</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/leistungsdaten/bericht.html\">Bericht des Aufgabenträgers</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/umweltschutz.html\">Umweltschutz</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/unternehmen/klimaschutz.html\">Klimaschutz</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/uitp.html\">UITP-Charta</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/umweltbericht.html\">Umweltbericht</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/leitstelle.html\">Leitstelle</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/geschichte/index.html\">Geschichte</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/unternehmen/geschichte/bis1980.html\">1876 - 1980</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/geschichte/bis_heute.html\">1985 - heute</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/cityservice/touren/seilbahn.html\">Kölner Seilbahn</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/spezial/orchester.html\">KVB-Orchester</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/spezial/orchester/repertoire.html\">Repertoire</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/spezial/orchester/leitung.html\">Musikalische Leitung</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/spezial/orchester/kontakt.html\">Kontakt</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/spezial/orchester/geschichte.html\">Geschichte</a></li>\n"
            + "</ul>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/museum/index.html\">Museum</a></li>\n"
            + "<ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/unternehmen/museum/anfahrt.html\">Anfahrt</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/museum/wissenswertes.html\">Wissenswertes</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/unternehmen/ausstellung/index.html\">Ausstellung</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"http://www.gasthaus-im-museum.de\">Gasthaus im Museum</a></li>\n"
            + "</ul>\n"
            + "</ul>\n"
            + "</li>\n"
            + "<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/karriere/index.html\">Jobs & Karriere</a></li>\n"
            + "<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/german/presse/index.html\">Presse</a><ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/presse/pressestelle.html\">Pressestelle</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/presse/pressemitteilungen.html\">Pressemitteilungen</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/spezial/dreh.html\">Drehgenehmigungen Fotoerlaubnis</a></li>\n"
            + "</ul>\n"
            + "</li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/home/kontakt.html\">Kontakt</a></li>\n"
            + "<li class=\"mobile_toplink\"><img src=\"/images/tpl/mobile_submenue_pfeil.png\" width=\"30\" height=\"30\" style=\"float:right;margin:-3% 3% 0 0;\" /><a href=\"/german/datenschutz/index.html\">Datenschutz</a><ul class=\"mobile_submenue\"><li class=\"mobile_toplink\"><a href=\"/german/datenschutz/haftung.html\">Haftungsausschluss</a></li>\n"
            + "<li class=\"mobile_toplink\"><a href=\"/german/datenschutz/verfahren.html\">Öffentliches Verfahrensverzeichnis</a></li>\n"
            + "</ul>\n"
            + "</li>\n"
            + "\t</ul>\n"
            + "\t</div>\n"
            + "</div>\n"
            + "<div id=\"gesamt\">\n"
            + "<a name=\"anfang\" id=\"anfang\"></a>\n"
            + "<div id=\"header\">\n"
            + "\t<a href=\"/german/home/index.html\"><img src=\"/images/tpl/header/9.jpg\" width=\"1004\" height=\"159\" title=\"KVB Koeln\" alt=\"KVB Koeln\" /></a>\n"
            + "</div>\n"
            + "<div id=\"subheader\">\n"
            + "\t<div class=\"floatleft font11\">\n"
            + "\t    <form method=\"post\" action=\"/suche/index.html\" id=\"searchForm\">\n"
            + "\t    <a href=\"javascript:OpenPrint('');\"><img src=\"/images/tpl/drucken.gif\" alt=\"Seite drucken\" title=\"Seite drucken\" class=\"floatleft\" style=\"padding: 9px 0px 0 0;\" width=\"44\" height=\"18\" /></a>\n"
            + "\t\t<input type=\"hidden\" name=\"SEARCHSTARTPATH\" value=\"/\" />\n"
            + "\t\t<input type=\"text\" name=\"SEARCHSTRING\" value=\"Suchtext\" onfocus=\"if(this.value == 'Suchtext') this.value='';\" onblur=\"if (this.value=='') this.value='Suchtext';\" class=\"suchfeld\" />\n"
            + "\t\t<input type=\"submit\" value=\"&raquo; Suchen\" style=\"font-family:verdana,arial;font-size:11px;color:#58595B;font-weight:normal;border:0px solid #eceded;background-color:#eceded;padding: 9px 5px 0 0;\" />\n"
            + "\t\t</form>\n"
            + "\t</div>\n"
            + "    <div style=\"float:right;width:703px;\">\n"
            + "        <a href=\"/stadtplan/\" title=\"Stadtplan\" style=\"padding-right:14px;\"><img src=\"/images/tpl/menue_stadtplan.jpg\" width=\"80\" height=\"37\" alt=\"Stadtplan\" title=\"Stadtplan\" class=\"floatleft\" style=\"margin-top:-2px;\" /></a>\n"
            + "\t\t<a href=\"https://www.facebook.com/kvb.ag\" title=\"Facebook\" class=\"submenue floatleft\" style=\"font-weight:normal;padding:4px 15px 0 2px;\" target=\"_blank\"><img src=\"/images/tpl/FB-f-Logo__blue_40.png\" width=\"25\" height=\"25\" alt=\"Facebook\" title=\"Facebook\" class=\"floatleft\" style=\"padding-top: 2px;\" /></a>\n"
            + "        <a href=\"http://www.instagram.com/kvbag\" title=\"Instagram\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:10px;\" target=\"_blank\"><img src=\"/images/tpl/Instagram_Icon-25.png\" width=\"25\" height=\"25\" alt=\"Instagram\" title=\"Instagram\" class=\"floatleft\" style=\"padding-top: 6px;\" /></a>\n"
            + "        <a href=\"http://www.youtube.com/KVBAG\" title=\"YouTube\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:7px;\" target=\"_blank\"><img src=\"/images/tpl/youtube.png\" width=\"59\" height=\"25\" alt=\"YouTube\" title=\"YouTube\" class=\"floatleft\" style=\"padding-top: 6px;\" /></a>\n"
            + "\t\t<a href=\"https://twitter.com/kvbag\" title=\"Twitter\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:10px;\" target=\"_blank\"><img src=\"/images/tpl/menue_twitter_50px.png\" width=\"40\" height=\"40\" alt=\"Twitter\" title=\"Twitter\" class=\"floatleft\" style=\"padding-top: 1px;\" /></a>\n"
            + "\t\t<a href=\"/german/adressen.html\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:14px;\" title=\"Adressen\">&raquo; Adressen</a>\n"
            + "        <a href=\"/karriere/stellenangebote.html\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:15px;\" title=\"Jobangebote\">&raquo; Jobangebote</a>\n"
            + "        <a href=\"/german/home/feedback.html\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:15px;\" title=\"Feedback\">&raquo; Feedback</a>\n"
            + "\t\t<a href=\"/german/downloads.html\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:15px;\" title=\"Downloads\">&raquo; Downloads</a>\n"
            + "\t\t<img src=\"/images/tpl/text_size.png\" usemap=\"#textsize\" width=\"51\" height=\"18\" alt=\"\" title=\"\" class=\"submenue floatleft\" style=\"float:right;margin-top:5px;\" />\n"
            + "\t\t<map id=\"textsize\" name=\"textsize\">\n"
            + "\t\t\t<area shape=\"rect\" href=\"#\" coords=\"5,0,20,18\" onclick=\"javascript:textSize(0);\" title=\"Text kleiner\" alt=\"Text kleiner\" style=\"cursor:pointer;\" />\n"
            + "\t\t\t<area shape=\"rect\" href=\"#\" coords=\"22,0,40,18\" onclick=\"javascript:textSize(1);\" title=\"Text größer\" alt=\"Text größer\" style=\"cursor:pointer;\" />\n"
            + "\t\t</map>\n"
            + "\t</div>\n"
            + "</div>\n"
            + "<div id=\"wrapper\">\n"
            + "\t<div id=\"menue\">\n"
            + "\t    <div id=\"menu\">\n"
            + "\t\t\t<div><ul>\t\t<li><a href='/german/home/index.html' class='h1' >Home</a></li>\n"
            + "\t\t<li><a href='/german/fahrplan/index.html' class='h1' >Fahrpläne und mehr</a></li>\n"
            + "\t\t<li><a href='/german/tarif/index.html' class='h1' >Tarife und Tickets</a></li>\n"
            + "\t\t<li><a href='/german/news/index.html' class='h1' >Neues und Service</a></li>\n"
            + "\t\t<li><a href='/german/kampagnen/index.html' class='h1' >Kampagnen</a></li>\n"
            + "\t\t<li><a href='/german/cityservice/index.html' class='h1' >Veranstaltungsinfos</a></li>\n"
            + "\t\t<li><a href='/german/unternehmen/index.html' class='h1' >Das Unternehmen</a></li>\n"
            + "\t\t<li><a href='/karriere/index.html' class='h1' >Jobs &amp; Karriere</a></li>\n"
            + "\t\t<li><a href='/german/presse/index.html' class='h1' >Presse</a></li>\n"
            + "\t\t<li><a href='/german/home/kontakt.html' class='h1' >Kontakt</a></li>\n"
            + "\t\t<li><a href='/german/datenschutz/index.html' class='h1' >Datenschutz</a></li>\n"
            + "\t\t<li><a href='http://svoe.zgk.de/cms/otc/e-magazines/koelntakt/flipviewerxpress.html' class='h1' target='_blank'>KölnTakt</a></li>\n"
            + "\t\t<li><span class='h1'> </span></li>\n"
            + "\t\t<li><span class='h1'> </span></li>\n"
            + "\t\t<li><a href='http://www.koelner-seilbahn.de/german/index.html' class='h1' target='_blank'>Kölner Seilbahn</a></li>\n"
            + "\t\t<li><a href='http://www.nord-sued-stadtbahn.de' class='h1' target='_blank'>Nord-Süd Stadtbahn</a></li>\n"
            + "\t\t<li><a href='http://www.hsk-koeln.de' class='h1' target='_blank'>Straßenbahn-Museum</a></li>\n"
            + "</ul></div>\t\t\t\t\t\t<br />\n"
            + "\t\t\t<div class=\"submenue font10\" style=\"padding-left:10px;\">\n"
            + "\t\t\t\t<a href=\"http://www.stadt-koeln.de/wirtschaft/marke-koeln/\" target=\"_blank\"><img src=\"/images/tpl/stadt-koeln.png\" width=\"142\" height=\"40\" alt=\"Stadt K&ouml;ln\" /></a>\n"
            + "\t\t\t\t<br /><br />\n"
            + "\t\t\t\t<a href=\"/german/sitemap/index.html\" class=\"submenue font10\" style=\"font-weight:normal;\" title=\"Sitemap\">Sitemap</a><br />\n"
            + "\t\t\t\t<a href=\"/german/impressum.html\" class=\"submenue font10\" style=\"font-weight:normal;\" title=\"Impressum\">Impressum</a><br />\n"
            + "                &copy; KVB AG 2016\t\t\t\t<br />\n"
            + "\t\t\t</div>\n"
            + "\t\t</div>\n"
            + "\t</div>\n"
            + "    <div id=\"content_wrapper\">\n"
            + "\t\t<div id=\"content\">\n"
            + "\t\t\t<!-- content -->\n"
            + "\t\t\t\n"
            + "\t\t\t<div class=\"fliesstext grau_bg grau_seiten\">\n"
            + "\t<!-- diff: 11 -->\n"
            + "\t\t\t<div class=\"qr_top_head_rot_small\">Fahrplanunregelmässigkeiten</div>\n"
            + "\t\t\t<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" class=\"qr_table\" style=\"border-bottom:8px solid #fff;\"><tr style=\"background-color:#ededed;\"><td class=\"qr_td\" style=\"padding:8px;font-size:0.85em;\" valign=\"center\">&nbsp;Derzeit liegen an dieser Haltestelle keine Störungen vor.</td></tr></table>\n"
            + "\t\t<div style=\"clear:both;\" class=\"qr_logo\">\n"
            + "\t\t    <div style=\"float:left;\"><img src=\"/images/qr/kvb_qr.png\" alt=\"Kölner Verkehrs-Betriebe AG\" /></div>\n"
            + "\t\t    <div style=\"float:right;vertical-align:middle;\"><span style=\"text-transform:none;font-weight:normal;letter-spacing:0;font-size: 0.85em;\"><!--Stand: 12:51 Uhr--><br />Alle Abfahrtzeiten<br />für die Haltestelle</span></div>\n"
            + "\t\t\t<br style=\"clear:both;\" />\n"
            + "\t\t</div>\n"
            + "\n"
            + "\t\t<div class=\"qr_top_head_rot_small\">Junkersdorf<span style=\"float:right;text-transform:none;font-weight:normal;letter-spacing:0;font-size: 0.85em;\" class=\"stand\">Stand: 12:51 Uhr&nbsp;&nbsp;</span></div>\n"
            + "\t\t<table width=\"100%\" cellpadding=\"2\" cellspacing=\"0\" class=\"qr_table\" style=\"border-bottom: 0px solid #fff;\"><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;E<!-- E -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Fahrt endet hier</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">3&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;144<!-- 144 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Bf Lövenich</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">5&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;141<!-- 141 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Vogelsang</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">6&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;143<!-- 143 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Lövenich</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">7&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;1<!-- 1 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Weiden West</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">7&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;1<!-- 1 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Bensberg</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">7&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;E<!-- E -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Fahrt endet hier</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">14&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;143<!-- 143 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Vogelsang</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">19&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;1<!-- 1 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Bensberg</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">21&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;1<!-- 1 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Weiden West</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">21&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;141<!-- 141 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Weiden Zentrum</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">22&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;141<!-- 141 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Vogelsang</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">34&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;144<!-- 144 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Bf Lövenich</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">35&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;1<!-- 1 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Weiden West</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">36&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;1<!-- 1 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Bensberg</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">36&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;143<!-- 143 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Lövenich</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">37&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;143<!-- 143 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Vogelsang</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">49&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;1<!-- 1 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Weiden West</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">50&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ededed;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;141<!-- 141 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Weiden Zentrum</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">51&nbsp;Min&nbsp;</td></tr><tr style=\"background-color:#ffffff;\"><td class=\"li_nr qr_td\" style=\"border-bottom:1px solid #ffffff;text-align:right;\" valign=\"top\">&nbsp;1<!-- 1 -->&nbsp;</td><td class=\"qr_td\" style=\"border-bottom:1px solid #ffffff;\">Bensberg</td><td class=\"qr_td\" style=\"text-align:right;border-bottom:1px solid #ffffff;\">51&nbsp;Min&nbsp;</td></tr></table><div style=\"clear:both;\"><br /><a href=\"/qr/haltestellen/\" style=\"font-size:1.1em;\"><b>&raquo; Weitere Haltestellen</b></a></div><div style=\"clear:both;\"><br /><a href=\"https://www.handyticket.de/portals/web/nutzer/kvb/login.html\" style=\"font-size:1.1em;\"><b>&raquo; Für das HandyTicket klicken Sie hier.</b></a></div>\t<br class=\"clear\" />\n"
            + "\t<br class=\"clear\" />\n"
            + "</div>\n"
            + "\n"
            + "\t\t\t<div id=\"mobil_impressum\">\n"
            + "\t\t\t\t<br style=\"clear:both;\" />\n"
            + "                <br style=\"clear:both;\" />\n"
            + "\t\t\t\t<br style=\"clear:both;display:none;\" class=\"mobileshow\" />\n"
            + "\t\t\t\t&copy; KVB AG 2016 | <a href=\"/german/impressum.html\" class=\"submenue font10\" style=\"font-weight:normal;\" title=\"Impressum\">Impressum</a> | <a href=\"/german/downloads.html\" class=\"submenue font10\" style=\"font-weight:normal;\" title=\"Downloads\">Downloads</a>\n"
            + "                <br />\n"
            + "\t\t\t\t<div style=\"margin-top:3%;\">\n"
            + "\t\t\t\t\t<center>\n"
            + "\t\t\t\t\t<a href=\"https://www.facebook.com/kvb.ag\" title=\"Facebook\" class=\"submenue floatleft\" style=\"font-weight:normal;padding:4px 5px 0 2px;\" target=\"_blank\"><img src=\"/images/tpl/FB-f-Logo__blue_40.png\" width=\"25\" height=\"25\" alt=\"Facebook\" title=\"Facebook\" style=\"padding-top: 2px;\" /></a>\n"
            + "        \t\t\t<a href=\"http://www.youtube.com/KVBAG\" title=\"YouTube\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:7px;\" target=\"_blank\"><img src=\"/images/tpl/youtube.png\" width=\"59\" height=\"25\" alt=\"YouTube\" title=\"YouTube\" style=\"padding-top: 6px;\" /></a>\n"
            + "\t\t\t\t\t<a href=\"https://twitter.com/kvbag\" title=\"Twitter\" class=\"submenue floatleft\" style=\"font-weight:normal;padding-right:0px;\" target=\"_blank\"><img src=\"/images/tpl/menue_twitter_50px.png\" width=\"40\" height=\"40\" alt=\"Twitter\" title=\"Twitter\" style=\"padding-top: 1px;\" /></a>\n"
            + "\t\t\t\t\t</center>\n"
            + "\t\t\t\t</div>\n"
            + "\t\t\t\t<br /><br />\n"
            + "\t\t\t</div>\n"
            + "\t\t\t<!-- /content -->\n"
            + "\t\t    <img src=\"/images/tpl/leer.gif\" alt=\"\" width=\"1\" height=\"1\" />\n"
            + "\t\t</div>\n"
            + "\t\t\t\t\t<div id=\"sidebar_right\">\n"
            + "\t\t\t<div class=\"clear\">\n"
            + "\t<span class=\"top_head_rot\">Fahrplanauskunft</span>\n"
            + "\t<div class=\"sidebar_rechts_kasten\" style=\"height:345px;\" >\n"
            + "\t\t<!-- start ass -->\n"
            + "    <iframe src=\"http://auskunft.kvb-koeln.de/kvb/kurzauskunft/kurzauskunft.html\" style=\"width:180px;margin:0;padding:0;border:0;height:225px;margin-left:-5px;overflow-y:hidden;overflow-x:hidden;background:#e3e3e4;\" frameborder=\"0\" border=\"0\" scrolling=\"no\" allowtransparency=\"true\"></iframe>\n"
            + "\t<!-- ende ass -->\n"
            + "    \t\t\t\t\t\t<div class=\"clear\">\n"
            + "    \t\t\t<span style=\"display:block;padding-top:8px;\">&nbsp;<a href=\"/german/fahrplan/minifahrplaene6.html\" class=\"font11\" style=\"font-family:Verdana;\"><b>&raquo; Minifahrpläne</b></a></span>\n"
            + "\t\t\t\t<span style=\"display:block;\">&nbsp;<a href=\"/german/fahrplan/aushangfahrplaene6.html\" class=\"font11\" style=\"font-family:Verdana;\"><b>&raquo; Aushangfahrpläne</b></a></span>\n"
            + "\t\t\t\t<div class=\"div100 floatleft clear submenue padding_b3 font11\">\n"
            + "\t\t\t\t\t<br /><b>Haltestelle suchen</b>\n"
            + "\t\t\t\t</div>\n"
            + "\t\t\t\t<div class=\"div100 floatleft clear submenue padding_b3 font11\">\n"
            + "\t\t\t\t\t<form action=\"/german/hst/search/\" method=\"post\">\n"
            + "\t\t\t\t\t\t<input type=\"text\" id=\"suggest1\" name=\"code\" value=\"\" class=\"fp_hst_input\" />\n"
            + "\t\t\t\t\t\t<!--<span style=\"display:block;text-align:left;padding-left:2px;padding-top:3px;padding-bottom:5px;\">-->\n"
            + "\t\t\t\t\t\t<input type=\"submit\" value=\"Haltestellensuche starten\" style=\"background-color:#FFFFFF;border: 1px solid #58595B;font-size:11px;font-family:Verdana;width:170px;display:block;text-align:center;margin-left:2px;margin-top:3px;margin-bottom:5px;clear:both;\" />\n"
            + "\t\t\t\t\t\t<!--</span>-->\n"
            + "\t\t\t\t\t</form>\n"
            + "\t\t\t\t</div>\n"
            + "\t\t\t\t<br style=\"clear:both;\" />\n"
            + "\t\t\t</div>\n"
            + "        <br style=\"clear:both;\" />\n"
            + "\t</div>\n"
            + "</div>\n"
            + "\n"
            + "<!-- Modul -->\n"
            + "<div style=\"border-bottom: 14px solid #ffffff;\" class=\"mofisanzeigen\">\n"
            + "\t\n"
            + "\t\t\t\t\n"
            + "\t<div id=\"tickerSidebar\"></div>\n"
            + "\t<script type=\"text/javascript\">\n"
            + "\t<!--\n"
            + "\t\n"
            + "\tfunction tickerSidebar(){\n"
            + "\t\t$(\"#tickerSidebar\").load('/mofis/ticker_sidebar.html', function(response, status, xhr) {\n"
            + "\t\t});\n"
            + "\t}\n"
            + "\ttickerSidebar();\n"
            + "\t//-->\n"
            + "\t</script>\n"
            + "\t\n"
            + "\t\t\n"
            + "</div>\n"
            + "\n"
            + "<div style=\"border-bottom:13px solid #ffffff;height:91px;\">\n"
            + "\t<div class=\"top_head_rot\">Kundencenter</div>\n"
            + "\t<a href=\"/german/kundencenter/index.html\"><img src=\"/images/kundencenter.gif\" width=\"190\"height=\"64\" alt=\"Kunden Center\" title=\"Kunden Center\" /></a>\n"
            + "</div>\n"
            + "<!-- /Modul -->\n"
            + "\n"
            + "<div style=\"border-bottom:13px solid #ffffff;\">\n"
            + "\t<div class=\"top_head_rot\">Infrastruktur</div>\n"
            + "    <div class=\"sidebar_rechts_kasten font10\" style=\"margin-bottom:0;border-bottom: 0px;\">\n"
            + "    \t<center><a href=\"http://www.damit-deutschland-vorne-bleibt.de\" target=\"_blank\"><img src=\"/images/tpl/ddvb.png\" width=\"180\" height=\"80\" alt=\"Damit Deutschland vorne bleibt - Initiative für eine zukunftsfähige Infrastruktur\" style=\"padding-bottom:5px;border-bottom:1px dotted #000000;\" /></a>\n"
            + "\t\t\n"
            + "\t\t</center>\n"
            + "\t</div>\n"
            + "\t<iframe src=\"http://www.damit-deutschland-vorne-bleibt.de/newsfeed-kvb.aspx?max=2\" width=\"190\" height=\"150\" name=\"Infrastruktur\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\" scrolling=\"no\" style=\"width:190px;clear:none;\"></iframe>\n"
            + "</div>\n"
            + "\n"
            + "<div>\n"
            + "    <span class=\"top_head_blau\">VDV</span>\n"
            + "    <div class=\"sidebar_rechts_kasten font10\" style=\"margin-bottom:0;border-bottom: 0px;\">\n"
            + "    \t<iframe src=\"http://www.vdv.de/aktuelles--teaser-kvb-koeln.aspx\" width=\"180\" height=\"435\" name=\"VDV\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\" scrolling=\"no\" style=\"width:180px;clear:none;\"></iframe>\n"
            + "\t</div>\n"
            + "</div>\n"
            + "\t\t</div>\n"
            + "\t\t\t</div>\n"
            + "</div>\n"
            + "</div>\n"
            + "<script type=\"text/javascript\" language=\"JavaScript\">\n"
            + "function OpenPrint(name) {\n"
            + "mywin=window.open('','PRINTFENSTER','width=800,height=600,menubar=yes,scrollbars=yes,resizable=yes');mywin.focus();\n"
            + "document.printform.PRINTTEMPLATE.value=name;\n"
            + "document.printform.submit();\n"
            + "}\n"
            + "</script>\n"
            + "<form name=\"printform\" action=\"\" method=\"post\" target=\"PRINTFENSTER\">\n"
            + "<input type=\"hidden\" name=\"PRINT\" value=\"1\" />\n"
            + "<input type=\"hidden\" name=\"PRINTTEMPLATE\" value=\"\" />\n"
            + "<input type=\"hidden\" name=\"service\" value=\"Links\" />\n"
            + "<input type=\"hidden\" name=\"curl\" value=\"\" />\n"
            + "</form>\n"
            + "<script src=\"/skripte/jquery.prettyPhoto.js\" type=\"text/javascript\"></script>\n"
            + "<script src=\"/skripte/jquery.autocomplete.min.js\" type=\"text/javascript\"></script>\n"
            + "<script type=\"text/javascript\">\n"
            + "<!--\n"
            + "$(document).ready(function(){\n"
            + "\n"
            + "\t$('.mobile_menu').hide();\n"
            + "\t$('#menubutton').click(function(e)\n"
            + "\t{\n"
            + "\t\tif($('#mobilemenuopen').css('display') == 'none')\n"
            + "\t\t{\n"
            + "\t\t$('#mobilemenuopen').css('display','block');\n"
            + "\t\t}\n"
            + "\t\t$('.mobile_menu').slideToggle('slow');\n"
            + "\t\te.preventDefault();\n"
            + "\t});\n"
            + "\t$('.mobile_toplink').click(function() {\n"
            + "          $('.mobile_submenue').slideUp('slow');\n"
            + "\t\tif($(this).find('.mobile_submenue').is(':visible')) {\n"
            + "\t\t}\n"
            + "\t\telse\n"
            + "\t\t{\n"
            + "              $(this).find('.mobile_submenue').slideDown('slow').all('.mobile_submenue').slideUp('slow');\n"
            + "\t\t}\n"
            + "\t});\n"
            + "\n"
            + "\n"
            + "        \n"
            + "\t/* lightbox */\n"
            + "\t$(\"a[rel^='lightbox']\").prettyPhoto();\n"
            + "\n"
            + "\t/* schnellsuche */\n"
            + "\t$('#schnellsuche_r input').keydown(function(e){\n"
            + "        if (e.keyCode == 13) {\n"
            + "            searchwin();\n"
            + "            $(this).parents('form').submit();\n"
            + "            return false;\n"
            + "        }\n"
            + "    });\n"
            + "\n"
            + "    var stations = [\"Aachener Str./Gürtel\", \"Adolf-Menzel-Str.\", \"Adrian-Meller-Str.\", \"Aeltgen-Dünwald-Str.\", \"Akazienweg\", \"Albin-Köbis-Straße\", \"Albrecht-Dürer-Platz\", \"Alfred-Schütte-Allee\", \"Alfter / Alanus Hochschule\", \"Alte Forststr.\", \"Alte Post\", \"Alte Römerstr.\", \"Alter Deutzer Postweg\", \"Alter Militärring\", \"Altonaer Platz\", \"Alzeyer Str.\", \"Am Bilderstöckchen\", \"Am Braunsacker\", \"Am Coloneum\", \"Am Emberg\", \"Am Faulbach\", \"Am Feldrain\", \"Am Grauen Stein\", \"Am Heiligenhäuschen\", \"Am Hetzepetsch\", \"Am Hochkreuz\", \"Am Kölnberg\", \"Am Kreuzweg\", \"Am Leinacker\", \"Am Lindenweg\", \"Am Neuen Forst\", \"Am Nordpark\", \"Am Portzenacker\", \"Am Schildchen\", \"Am Serviesberg\", \"Am Springborn\", \"Am Steinneuerhof\", \"Am Vorgebirgstor\", \"Am Weißen Mönch\", \"Am Zehnthof\", \"Amselstr.\", \"Amsterdamer Str./Gürtel\", \"An den Kaulen\", \"An der alten Post\", \"An der Ronne\", \"An der Walkmühle\", \"An St. Marien\", \"Andreaskloster\", \"Anemonenweg\", \"Antoniusstr.\", \"Appellhofplatz\", \"Arenzhof\", \"Arnoldshöhe\", \"Arnulfstr.\", \"Arthur-Hantzsch-Str.\", \"Auf dem Streitacker\", \"Auf der Freiheit\", \"August-Horch-Str.\", \"Auguste-Kowalski-Str.\", \"Autobahn\", \"Auweiler\", \"Auweilerweg\", \"Bachemer Str.\", \"Bachstelzenweg\", \"Bad Godesb. Bf/Löbestr.\", \"Badorf\", \"Bahnstr.\", \"Baldurstr.\", \"Baptiststr.\", \"Barbarastr.\", \"Barbarossaplatz\", \"Baumschulenweg\", \"Bayenthalgürtel\", \"Chempark S-Bahn\", \"Beethovenstr.\", \"Bensberg\", \"Bergheim Friedhof\", \"Bergheim Fährhaus\", \"Bergheim Grundschule\", \"Bergheim Industriegebiet\", \"Bergheim Kirche\", \"Bergstr.\", \"Bernkasteler Str.\", \"Berrenrather Str.\", \"Berrenrather Str./Gürtel\", \"Betzdorfer Str.\", \"Beuelsweg\", \"Beuelsweg Nord\", \"Beuthener Str.\", \"Bevingsweg\", \"Bf Deutz/LANXESS arena\", \"Bf Deutz/Messe\", \"Bf Deutz/Messeplatz\", \"Bf Ehrenfeld\", \"Bf Lövenich\", \"Bf Mülheim\", \"Bf Porz\", \"Bieselweg\", \"Birkenallee\", \"Birkenweg\", \"Bismarckstr.\", \"Bistritzer Str.\", \"Bitterstr.\", \"Blaugasse\", \"Blériotstr.\", \"Blockstr.\", \"Bocklemünd\", \"Bodinusstr.\", \"Boltensternstr.\", \"Bonhoefferstr.\", \"Bonn Bertha-von-Suttnerplatz\", \"Bonn West\", \"Bonner Landstr.\", \"Bonner Str.\", \"Bonner Wall\", \"Bonner Str./Gürtel\", \"Bonntor\", \"Bornheim\", \"Bornheim Rathaus\", \"Borsigstr.\", \"Brahmsstr.\", \"Braugasse\", \"Bremerhavener Str.\", \"Breslauer Platz/Hbf\", \"Broichstr.\", \"Bruder-Klaus-Siedlung\", \"Brück Mauspfad\", \"Brüggener Str.\", \"Brühl Mitte\", \"Brühl Nord\", \"Brühl Süd\", \"Brühl-Vochem\", \"Brühler Str./Gürtel\", \"Brühler Straße\", \"Btf. Merheim\", \"Buchforst S-Bahn\", \"Buchforst Waldecker Str.\", \"Buchheim Frankfurter Str.\", \"Buchheim Herler Str.\", \"Buchheimer Weg\", \"Bundesrechnungshof\", \"Bunsenstr.\", \"Burgwiesenstr.\", \"Buschdorf\", \"Buschfeldstr.\", \"Buschweg\", \"Sparkasse Am Butzweilerhof\", \"Butzweilerstr.\", \"Bückebergstr.\", \"Böcklinstr.\", \"Bödinger Str.\", \"Carl-Goerdeler-Str.\", \"Cheruskerstr.\", \"Chlodwigplatz\", \"Chorbuschstr.\", \"Chorweiler\", \"Christophstr./Mediapark\", \"Clarenbachstift\", \"Colonia-Allee\", \"Cranachstr.\", \"Cäsarstr.\", \"CöllnParc\", \"Dasselstr./Bf Süd\", \"Deckstein\", \"Dellbrück Hauptstr.\", \"Dellbrück Mauspfad\", \"Dellbrück S-Bahn\", \"Dersdorf\", \"Ollenhauerstraße\", \"Olof-Palme-Allee\", \"Deutz Technische Hochschule\", \"Deutzer Freiheit\", \"Deutzer Friedhof\", \"Deutzer Ring\", \"Diepenbeekallee\", \"Diepeschrather Str.\", \"Dieselstr.\", \"Dionysstr.\", \"DLR\", \"Dohmengasse\", \"Dom/Hbf\", \"Donatusstr.\", \"Dornstr.\", \"Dorotheenstraße\", \"Dr.-Schultz-Str.\", \"Dransdorf\", \"Drehbrücke\", \"Drosselweg\", \"Dünnwald Waldbad\", \"Dünnwalder Str.\", \"Dürener Str./Gürtel\", \"Dädalusring\", \"Ebernburgweg\", \"Ebertplatz\", \"Ebertplatz/Riehler Str.\", \"Eddaweg\", \"Edelhofstr.\", \"Edmund-Rumpler-Str.\", \"Edsel-Ford-Str.\", \"Efferen\", \"Egelspfad\", \"Eggerbachstr.\", \"Egonstr.\", \"Eichenstr.\", \"Eifelplatz\", \"Eifelstr.\", \"Eifelwall\", \"Eil Heumarer Str.\", \"Eil Kirche\", \"Eiler Str.\", \"Elisabethstr.\", \"Elsdorf\", \"Emilstr.\", \"Engeldorfer Hof\", \"Engeldorfer Str.\", \"Ensen Gilgaustr.\", \"Ensen Kloster\", \"Erlenweg\", \"Ernst-Volland-Str.\", \"Esch\", \"Esch Friedhof\", \"Escher See\", \"Escher Str.\", \"Eschmar Bergheimer Str.\", \"Eschmar Kirche\", \"Esserstr.\", \"Esso\", \"Ettore-Bugatti-Straße\", \"Etzelstr.\", \"Eupener Str.\", \"Europaring\", \"Euskirchener Str.\", \"Eythstr.\", \"Falkenweg\", \"Feldbergstr.\", \"Feldkasseler Weg\", \"Feltenstr.\", \"Feuerwache\", \"Fischenich\", \"Flachsweg\", \"Flehbachstr.\", \"Flittard Süd\", \"Flittarder Feld\", \"Florastr.\", \"Florenzer Str.\", \"Flughafen Verwaltung\", \"Fordwerke Mitte\", \"Fordwerke Nord\", \"Fordwerke Süd\", \"Frankenforst\", \"Frankenforst\", \"Frankenstr.\", \"Frankenthaler Str.\", \"Frankfurter Str. S-Bahn\", \"Frankstr.\", \"Franziska-Anneke-Str.\", \"Frechen Bf\", \"Frechen Kirche\", \"Frechen Rathaus\", \"Frechen-Benzelrath\", \"Frechener Weg\", \"Freiheitsring\", \"Freiligrathstr.\", \"Friedensstr.\", \"Friedhof Chorweiler\", \"Friedhof Godorf\", \"Erker Mühle\", \"Friedhof Stammheim\", \"Friedhof Steinneuerhof\", \"Friedhof Worringen\", \"Friedrich-Hirsch-Str.\", \"Friedrich-Karl-Str./Neusser Str.\", \"Friedrich-Karl-Str./Niehler Str.\", \"Friesenplatz\", \"Fuldaer Str.\", \"Further Str.\", \"Fühlingen\", \"Fühlinger Weg\", \"Gaedestr.\", \"Gauweg\", \"Gebr.- Coblenz-Str.\", \"Geestemünder Str.\", \"Geibelstr.\", \"Geisselstr.\", \"Geldernstr./Parkgürtel\", \"Gerhart-Hauptmann-Str.\", \"Gewerbegebiet Broichstr.\", \"Gewerbegebiet Pesch\", \"Gewerbegebiet Pesch Nord\", \"Gießener Str.\", \"Gisbertstr.\", \"Glashüttenstr.\", \"Gleueler Str./Gürtel\", \"Godorf Bf\", \"Goldammerweg\", \"Goldregenweg\", \"Goltsteinstr./Gürtel\", \"Gottesweg\", \"Grachtenhofstr.\", \"Graditzer Str.\", \"Graf-Adolf-Str.\", \"Gremberg\", \"Grengel Mauspfad\", \"Grevenbroicher Str.\", \"Grimmelshausenstr.\", \"Gronauer Str.\", \"Grunerstr.\", \"Grüner Weg\", \"Grüngürtelstr.\", \"Grünstr.\", \"Gunther-Plüschow-Str.\", \"Guntherstr.\", \"Gut Neuenhof\", \"Gutenbergstr.\", \"Gürzenichstr.\", \"Güterverkehrszentrum\", \"Görlinger Zentrum\", \"Göttinger Str.\", \"Habichtstraße\", \"Hackhauser Weg\", \"Hagenstr.\", \"Hahnwald\", \"Hahnwald Im Hasengarten\", \"Hahnwaldweg\", \"Halfengasse\", \"Hammerschmidtstr.\", \"Hans-Böckler-Platz/Bf West\", \"Hansaring\", \"Hansestr.\", \"Hansestr. Ost\", \"Hansestr. Süd\", \"Hansestr. West\", \"Bonn Hauptbahnhof\", \"Haus Fühlingen\", \"Haus Vorst\", \"Havelstr.\", \"Heeresamt\", \"Heimersdorf\", \"Heinering\", \"Heinrich-Lübke-Ufer\", \"Heinrich-Mann-Str.\", \"Heinrich-Steinmann-Str.\", \"Heinz-Kühn-Str.\", \"Herforder Str.\", \"Hermann-Löns-Str.\", \"Herrigergasse\", \"Hersel\", \"Herstattallee\", \"Herthastr.\", \"Heumarkt\", \"Heussallee/Museumsmeile\", \"Hildegardis-Krankenhaus\", \"Hildegundweg\", \"Hochkirchen\", \"Hochkreuz\", \"Hohenlind\", \"Holweide S-Bahn\", \"Holweide Vischeringstr.\", \"Honschaftsstr.\", \"Hopfenstr.\", \"Hugo-Eckener-Str.\", \"Hugo-Junkers-Str.\", \"Humboldtstr.\", \"Hücheln Krankenhaus\", \"Hüchelner Str.\", \"Hürth-Hermülheim\", \"Hürth Kalscheuren Bf\", \"Häuschensweg\", \"Höhenberg Frankfurter Str.\", \"Höhscheider Weg\", \"Höningen Rondorfer Weg\", \"Höningen Siedlung\", \"IKEA Am Butzweilerhof\", \"IKEA Godorf\", \"Iltisstr.\", \"Im Buschfelde\", \"Im Falkenhorst\", \"Im Hoppenkamp\", \"Im Klarenpesch\", \"Im Langen Bruch\", \"Im Rheinpark\", \"Im Wasserfeld\", \"Im Weidenbruch\", \"Im Wichemshof\", \"Im Wirtskamp\", \"Imbacher Weg\", \"Imbuschstr.\", \"Immendorf\", \"Immendorf Schule\", \"Immendorf Siedlung\", \"Indianapolis-Straße\", \"Innere Kanalstr.\", \"Jasminweg\", \"Johannes-Prassel-Str.\", \"Johannesstr.\", \"Josef-Lammerting-Allee\", \"Josephstr.\", \"Junkersdorf\", \"Juridicum\", \"Justizzentrum\", \"Kalk Kapelle\", \"Kalk Post\", \"Kalker Friedhof\", \"Kalkweg\", \"Kalscheurer Weg\", \"Kapellenweg\", \"Kapfenberger Str.\", \"Kartäuserhof\", \"Karl-Marx-Allee\", \"Karl-Schwering-Platz\", \"Karnevalsmuseum\", \"Kaserne Haupttor\", \"Kaserne Nordtor\", \"Kasselberg\", \"Katharinenhof\", \"Kendenicher Str.\", \"Kesselsgasse\", \"Kettelerstr.\", \"Keupstr.\", \"Kiebitzweg\", \"Kieler Str.\", \"Kierberger Str.\", \"Kinderkrankenhaus\", \"Kippekausen\", \"Kirschbaumweg\", \"Kitschburger Str.\", \"Kleinfeldchensweg\", \"Klettenbergpark\", \"Klingerstr.\", \"Klinikum Merheim\", \"Klosterhof\", \"Koblenzer Str.\", \"Kochwiesenstr.\", \"Koelnmesse\", \"Kolkrabenweg\", \"Konrad-Adenauer-Str.\", \"Konradstr.\", \"Kopernikusschule\", \"Koppensteinstr.\", \"Kornblumenweg\", \"Krefelder Wall\", \"Kretzerstr.\", \"Krieler Str.\", \"Kuenstr.\", \"Kühzällerweg\", \"Kürtenstr.\", \"Kämpchensweg\", \"Alter Flughafen Butzweilerhof\", \"Köln/Bonn Flughafen\", \"Kölner Str.\", \"Kölner Weg\", \"Kölnstr.\", \"Königsforst\", \"Körnerstr.\", \"Lacher Broch\", \"Lahnstr.\", \"Langel Fähre\", \"Langel Kuhlenweg\", \"Langel Mohlenweg\", \"Langel Nord\", \"Friedhof Lehmbacher Weg\", \"Leiblplatz\", \"Leichweg\", \"Leimbachweg\", \"Leinsamenweg\", \"Leipziger Platz\", \"Lenauplatz\", \"Leopold-Gmelin-Str.\", \"Lerchenweg\", \"Lessingstr.\", \"Leuchterstr.\", \"Leyboldstr.\", \"Leyendeckerstr.\", \"Liblarer Str.\", \"Libur Kirche\", \"Libur Margaretenstr.\", \"Liebigstr.\", \"Lindenburg\", \"Lindenbuschweg\", \"Lindenweg\", \"Linder Kreuz\", \"Linder Mauspfad\", \"Linder Weg\", \"Lindweilerfeld\", \"Lindweilerweg\", \"Lippeweg\", \"Lohsestr.\", \"Longerich Friedhof\", \"Longerich S-Bahn\", \"Longericher Str.\", \"Longericher Str. Nord\", \"Longericher Str./Etzelstr.\", \"Lucasstr.\", \"Ludwig-Quidde-Platz\", \"Ludwigsburger Str.\", \"Luftfracht Köln/Bonn\", \"Lustheide\", \"LVR-Klinik\", \"Lülsdorf Hallenbad\", \"Lülsdorf Kirche\", \"Lülsdorf Nord\", \"Lülsdorf Schulzentrum\", \"Lülsdorf Uhlandstr.\", \"Maarhäuser Weg\", \"Maarweg\", \"Mannesmannstr.\", \"Mannsfeld\", \"Marconistr.\", \"Marconistr. Ost\", \"Margaretastr.\", \"Maria-Himmelfahrt-Str.\", \"Marienberger Weg\", \"Marienburg Südpark\", \"Marienburger Str.\", \"Marienplatz\", \"Marienstr.\", \"Marktplatz Sürth\", \"Marktstr.\", \"Marsdorf\", \"Maternusplatz\", \"Mathias-Brüggen-Str.\", \"Mauritiuskirche\", \"Mauritiusschule\", \"Max-Löbner-Str./Friesdorf\", \"Mechternstr.\", \"Meerfeldstr.\", \"Melaten\", \"Melli-Beese-Str.\", \"Mennweg\", \"Merheim\", \"Merheimer Platz\", \"Merianstr.\", \"Merkenich\", \"Merkenich Mitte\", \"Merkenicher Str.\", \"Merten\", \"Meschenich Kirche\", \"Messe Omnibushof\", \"Methweg\", \"Metternicherstr.\", \"Michelshoven\", \"Militärringstr.\", \"Mohnweg\", \"Mollwitzstr.\", \"Moltkestr.\", \"Mommsenstr.\", \"Mondorf Ahrstr.\", \"Mondorf Beckergasse\", \"Mondorf Provinzialstr.\", \"Mondorf Rosenthalstr.\", \"Mondorf Sportplatz\", \"Montanusstr.\", \"Morsestr.\", \"Moses-Hess-Str.\", \"Mozartstr.\", \"Museum Koenig\", \"Mutzbach\", \"Mühlengasse\", \"Mühlenweg\", \"Mühlenweiher\", \"Mülhauser Str.\", \"Mülheim Berliner Str.\", \"Mülheim Wiener Platz\", \"Mülheimer Friedhof\", \"Mülheimer Ring\", \"Müllekoven\", \"Müngersdorf S-Bahn/Technologiepark\", \"Nachtigallenstr.\", \"Nattermannallee\", \"Neißestr.\", \"Nesselrodestr.\", \"Neuenweg\", \"Neuer Mülheimer Friedhof\", \"Neufelder Str.\", \"Neufeldweg\", \"Neumarkt\", \"Neurather Weg\", \"Neusser Str./Gürtel\", \"Neven DuMont Haus\", \"Nibelungenplatz\", \"Nibelungenstr.\", \"Niederkassel Evgl. Kirche\", \"Niederkassel Nord\", \"Niederkassel Rathausplatz\", \"Niederkassel Spicher Str.\", \"Niederkassel Waldstr.\", \"Niehl\", \"Niehl Sebastianstr.\", \"Niehler Damm\", \"Niehler Kirchweg\", \"Niehler Str.\", \"Nievenheimer Str.\", \"Nippes S-Bahn\", \"Nordfriedhof\", \"Nordstr.\", \"Nußbaumerstr.\", \"Nüssenberger Str.\", \"Oberer Komarweg\", \"Oberlar Landgrafenstr\", \"Oberlar Lindlaustr.\", \"Friedenspark\", \"Oberzündorf\", \"Odenthaler Str.\", \"Ollenhauerring\", \"Olpener Str.\", \"Oranienstr.\", \"Oranjehofstr.\", \"Oskar-Jäger-Str.\", \"Oskar-Jäger-Str./Gürtel\", \"Ossendorf\", \"Osterather Str.\", \"Ostfriedhof\", \"Ostheim\", \"Ostlandstr.\", \"Ostmerheimer Str.\", \"Otto-Hahn-Str.\", \"Otto-Müller-Str.\", \"Palmenhof\", \"Pasteurstr.\", \"Paul-Reifenberg-Str.\", \"Pesch Schulstr.\", \"Pescher Weg\", \"Pettenkoferstr.\", \"Pierstr.\", \"Piusstr.\", \"Plittersdorfer Straße\", \"Pohligstr.\", \"Poll Hauptstr.\", \"Poll Salmstr.\", \"Poller Holzweg\", \"Poller Kirchweg\", \"Porz Markt\", \"Porz Steinstr.\", \"Porz-Langel Kirche\", \"Porz-Langel Mühle\", \"Porz-Langel Nord\", \"Porz-Langel Süd\", \"Porz-Langel Zur Eiche\", \"Porzer Str.\", \"Poststr.\", \"Propsthof Nord\", \"Prälat-van-Acken-Str.\", \"Pulheimer Str.\", \"Raiffeisenstr.\", \"Ramersdorf\", \"Ramrather Weg\", \"Ranzel Gewerbegebiet\", \"Ranzel Kirche\", \"Ranzel Schule\", \"Ranzel Schulstr.\", \"Ranzel Sonnenbergerweg\", \"Ranzel Weilerhof\", \"Rath-Heumar\", \"Rathaus\", \"Rathenaustr.\", \"Refrath\", \"Reichenspergerplatz\", \"Reiherstr.\", \"Reischplatz\", \"Rektor-Klein-Str.\", \"Remscheider Str.\", \"Rheidt Bahnhofstr.\", \"Rheidt Markt\", \"Rheidt Nord\", \"Rheidt Süd\", \"Rheidt Unterführung\", \"Rheinauhafen\", \"Rheinbergstr.\", \"Rheinenergie-Stadion\", \"Rheinkassel\", \"Rheinlandstr.\", \"Rheinsteinstr.\", \"Rhöndorfer Str.\", \"Richard-Wagner-Str.\", \"Riehl Betriebshof Nord\", \"Riehler Gürtel\", \"Ritterstr.\", \"Robert-Bosch-Str.\", \"Robert-Kirchhoff-Straße\", \"Robert-Perthel-Str.\", \"Robert-Schuman-Platz\", \"Rodenkirchen Bf\", \"Rodenkirchen Bismarckstr.\", \"Rodenkirchen Rathaus\",\"Rodenkirchener Str.\", \"Roggenweg\", \"Roisdorf West\", \"Roisdorfer Str.\", \"Rolandstr.\", \"Rolshover Str.\", \"Rondorf\", \"Roonstr.\", \"Rosenhügel\", \"Rosenstr.\", \"Rosmarinweg\", \"Rotdornweg\", \"Roteichenweg\", \"Rudolf-Diesel-Str.\", \"Rudolfplatz\", \"Rösrather Str.\", \"Röttgensweg\", \"Saarbrücker Str.\", \"Saarstr.\", \"Sachsenbergstr.\", \"Sauerlandstr.\", \"Schadowstr.\", \"Schaffrathsgasse\", \"Schanzenstr./Schauspielhaus\", \"Scheibenstr.\", \"Scheuermühlenstr.\", \"Schillingsrotter Str.\", \"Schirmerstr.\", \"Schlagbaumsweg\", \"Schlebusch\", \"Schlehdornstr.\", \"Schlettstadter Str.\", \"Schloss Röttgen\", \"Schmiedegasse\", \"Schneider-Clauss-Str.\", \"Schokoladenmuseum\", \"Schulzentrum Wahn\", \"Schumacherring\", \"Schwabenstr.\", \"Schwadorf\", \"Schwarzrheindorf Kirche\", \"Schwarzrheindorf Schule\", \"Schwarzrheindorf Siegaue\", \"Schwindstr.\", \"Schüttewerk\", \"Schönhauser Str.\", \"Sechzigstr.\", \"Seeberg\", \"Seithümerstr.\", \"Selma-Lagerlöf-Str.\", \"Seniorenzentrum Riehl\", \"Servatiusstr.\", \"Severinsbrücke\", \"Severinskirche\", \"Severinstr.\", \"Severinusstr.\", \"Siebengebirgsallee\", \"Siedlung Mielenforst\", \"Siegburg Bf\", \"Siegburg Brückberg\", \"Siegburg Ernststr.\", \"Siegburg Friedrich-Ebert-Str.\", \"Siegburg Heinrichstr.\", \"Siegburg Kaiserstr.\", \"Siegburg Kaserne\", \"Siegburg Markt\", \"Siegburg Stadthalle\", \"Siegburg Waldstr.\", \"Siegburg Zum Hohen Ufer\", \"Siegburger Str.\", \"Siegfriedstr.\", \"Sieglar Feuerwache\", \"Sieglar Flachtenstr./Krankenhaus\", \"Sieglar Im Kirschtal\", \"Sieglar Leostr.\", \"Sieglar Rathausstr.\", \"Sieglar Rathausstr./Kreisel\", \"Sieglar RSVG\", \"Sieglar Schulzentrum\", \"Siegstr.\", \"Siemensstr.\", \"Sigwinstr.\", \"Silbermöwenweg\", \"Sinnersdorf Kirche\", \"Sinnersdorfer Mühle\", \"Slabystr.\", \"Sparkasse\", \"Spitzangerweg\", \"Sportplatzstr.\", \"Sprengelstr.\", \"St. Vincenz Haus\", \"St. Vinzenz-Hospital\", \"St.-Tönnis-Str.\", \"St.Joseph-Kirche\", \"Bonn Bad Godesberg Stadthalle\", \"Stallagsweg\", \"Stammheim S-Bahn\", \"Stammheimer Ring\", \"Stegerwaldsiedlung\", \"Steinkauzweg\", \"Steinmetzstr.\", \"Steinstr. S-Bahn\", \"Steinweg\", \"Sterrenhofweg\", \"Stiftsstr.\", \"Stolberger Str.\", \"Stolberger Str./Eupener Str.\", \"Stolberger Str./Maarweg\", \"Stommeler Str.\", \"Stormstr.\", \"Straßburger Platz\", \"Stresemannstr.\", \"Stüttgenhof\", \"Stüttgerhofweg\", \"Subbelrather Str./Gürtel\", \"Suevenstr.\", \"Südallee\", \"Südbahnhof\", \"Sülz Hermeskeiler Platz\", \"Sülzburgstr.\", \"Sülzburgstr./Berrenrather Str.\", \"Sülzgürtel\", \"Sürth Bf\", \"Tacitusstr.\", \"Takustr.\", \"Talweg\", \"Tannenbusch Mitte\", \"Tannenbusch Süd\", \"Taubenholzweg\", \"Technologiepark Köln\", \"TechnologiePark Mitte\", \"Theodor-Heuss-Str.\", \"Theresienstr.\", \"Thermalbad\", \"Thielenbruch\", \"Thurner Kamp\", \"Totilastr.\", \"Trifelsstr.\", \"Trimbornstr.\", \"Troisdorf Aggerbrücke\", \"Troisdorf Altenforst\", \"Troisdorf Bergeracker\", \"Troisdorf BF\", \"Troisdorf Elsenplatz\", \"Troisdorf Kuttgasse\", \"Troisdorf Rathaus\", \"Troisdorf Ursulaplatz\", \"Troisdorf Wilhelmstr.\", \"Troisdorfer Str.\", \"TÜV-Akademie\", \"Ubierring\", \"Uedorf\", \"Uferstr.\", \"Ulrepforte\", \"Universitaet/Markt\", \"Universität\", \"Universitätsstr.\", \"Unnauer Weg\", \"Urbach Breslauer Str.\", \"Urbach Friedhof\", \"Urbach Kaiserstr.\", \"Urbach Waldstr.\", \"Urfeld\", \"Venloer Str./Gürtel\", \"Vingst\", \"Vitalisstr. Nord\", \"Vitalisstr. Süd\", \"Vogelsanger Markt\", \"Vogelsanger Str.\", \"Vogelsanger Str./Maarweg\", \"Vogelsanger Weg\", \"Volkhovener Weg\", \"Voltastr.\", \"Von-Galen-Str.\", \"Von-Hünefeld-Str.\", \"Von-Lohe-Str.\", \"Von-Quadt-Str.\", \"Von-Sparr-Str.\", \"Wahn Friedhof\", \"Wahn Kirche\", \"Wahn S-Bahn\", \"Waidmarkt\", \"Walberberg\", \"Waldorf\", \"Waldstr.\", \"Waldstr./Akazienweg\", \"Walter-Dodde-Weg\", \"Walter-Pauli-Ring\", \"Wasserwerk\", \"Wattstr.\", \"WDR\", \"Weichselring\", \"Weiden Einkaufszentrum\", \"Weiden Goethestr.\", \"Weiden Schulstr.\", \"Weiden Sportplatz\", \"Weiden West S-Bahn\", \"Weiden Zentrum\", \"Weidenpescher Str.\", \"Weilburger Str.\", \"Weiler\", \"Weilerweg\", \"Weinsbergstr./Gürtel\", \"Weiß Friedhof\", \"Weißer Hauptstr.\", \"Weißhausstr.\", \"Welserstr.\", \"Wendelinstr.\", \"Weserpromenade\", \"Wesseling\", \"Wesseling Nord\", \"Wesseling Süd\", \"Wesselinger Str.\", \"Westerwaldstr.\", \"Westfriedhof\", \"Westhoven Berliner Str.\", \"Westhoven Kölner Str.\", \"Weyertal\", \"Wezelostr.\", \"Wichheimer Str.\", \"Widdersdorf\", \"Widdersdorfer Str.\", \"Widdig\", \"Wiedenfelder Weg\", \"Wiedstr.\", \"Wiehler Str.\", \"Wiener Weg\", \"Wiesenweg\", \"Wildpark\", \"Wilhelm-Sollmann-Str.\", \"Wilhelmstr.\", \"Willi-Lauf-Allee\", \"Windmühlenstr.\", \"Wingertsheide\", \"Wiso-Fakultät\", \"Wolffsohnstr.\", \"Worringen S-Bahn\", \"Worringen Süd\", \"Worringer Str.\", \"Wurzerstraße\", \"Wüllnerstr.\", \"Würzburger Str.\", \"Xantener Str.\", \"Üdesheimer Weg\", \"Üsdorf\", \"Zaunhof\", \"Zaunstr.\", \"Zollstock Südfriedhof\", \"Zollstockgürtel\", \"Zollstocksweg\", \"Zonser Str.\", \"Zoo/Flora\", \"Zum Hedelsberg\", \"Zum Neuen Kreuz\", \"Zur Abtei\", \"Zülpicher Platz\", \"Zülpicher Str./Gürtel\", \"Zündorf\", \"Zündorf Altersheim\", \"Zündorf Kirche\", \"Zündorf Marktstr.\", \"Zündorf Mitte\", \"Zündorf Olefsgasse\", \"Zündorf Ranzeler Str.\", \"Zündorfer Weg\", \"Zypressenstr.\", \"Äußere Kanalstr.\", \"Carlswerkstraße\", \"Schanzenstr. Nord\", \"Belvederestr.\", \"Paul-Nießen-Str.\", \"Im Rheintal\", \"Lüderichstr.\", \"Volksgarten\", \"Zugweg\", \"Celsiusstr.\", \"Wilhelm-Leuschner-Str.\",\"Corintostraße\",\"Kalk-Karree\",\"Christian-Sünner-Straße\",\"Heinrich-Bützler-Straße\",\"Gummersbacher Straße\", \"Lentpark\", \"Curt-Stenvert-Bogen\", \"Gut Leidenhausen\", \"Klaprothstr.\", \"Kallbergstr.\", \"Blumenberg S-Bahn\", \"Oskar-Schindler-Str.\", \"Am Eifeltor\", \"Elisabeth-Breuer-Str.\", \"Schützenhofstr.\", \"Lina-Bommer-Weg\", \"Hans-Offermann-Str.\", \"Bertha-Benz-Karree\"];\n"
            + "\n"
            + "    function findValue(li) {\n"
            + "\t\tif( li == null ) return alert(\"Keine Treffer\");\n"
            + "\t\tif( !!li.extra ) var sValue = li.extra[0];\n"
            + "\t\telse var sValue = li.selectValue;\n"
            + "\t}\n"
            + "\n"
            + "\tfunction selectItem(li) {\n"
            + "\t\tfindValue(li);\n"
            + "\t}\n"
            + "\n"
            + "\t$(\"#suggest1\").blur().autocomplete(stations, {\n"
            + "\t\tdelay:250,\n"
            + "\t\tminChars:1,\n"
            + "\t\tmatchSubset:1,\n"
            + "\t\tmatchContains:1,\n"
            + "\t\tcacheLength:10,\n"
            + "\t\twidth:150,\n"
            + "\t\tonItemSelect:selectItem,\n"
            + "\t\tautoFill:false,\n"
            + "\t\tmax: 15\n"
            + "\t});\n"
            + "\t\n"
            + "\t/* faq */\n"
            + "\tjQuery('.answer').hide();\n"
            + "\tjQuery('.question').click(function() {\n"
            + "\t    if(jQuery(this).next('.answer').is(':visible')) {\n"
            + "\t        jQuery(this).next('.answer').slideUp(200);\n"
            + "\t    } else {\n"
            + "\t        jQuery(this).next('.answer').slideDown(200).siblings('.answer').slideUp(200);\n"
            + "\t    }\n"
            + "\t});\n"
            + "\n"
            + "    \t$('.qr_toggle_btn').click(function() {\n"
            + "\t  $('.qr_toggle').toggle('slow', function() {\n"
            + "\t  });\n"
            + "\t});\n"
            + "    \n"
            + "\t});\n"
            + "\n"
            + "\n"
            + "var fontsize=13;\n"
            + "function textSize(dec) {\n"
            + "\tfontsize+=(dec==1)?1:(-1);\n"
            + "\tif(fontsize<1) fontsize=1;\n"
            + "\tdocument.getElementById(\"content\").style.fontSize=\"\"+fontsize+\"px\";\n"
            + "}\n"
            + "\n"
            + "function download_select_box(id_name)\n"
            + "{\n"
            + "    var target_url = document.getElementById(id_name).value;\n"
            + "\twindow.open(target_url);\n"
            + "}\n"
            + "\n"
            + "//-->\n"
            + "</script>\n"
            + "</center>\n"
            + "\n"
            + "</body>\n"
            + "</html>";
}
